export interface City {
  name: string;
  slug: string;
  postalCode: string;
  description: string;
  lat: number;
  lng: number;
  population: number;
  quartiers: string[];
  problemesFrequents: string[];
  atout: string;
}

export const cities: City[] = [
  { name: "Argenteuil", slug: "argenteuil", postalCode: "95100", description: "Plus grande ville du Val d'Oise, réseaux anciens du centre-ville et grands ensembles des années 60-70 avec canalisations en fonte vieillissantes.", lat: 48.9472, lng: 2.2467, population: 113748, quartiers: ["Val-d'Argent", "Orgemont", "Centre-ville", "Côteau"], problemesFrequents: ["Fonte vétuste dans les immeubles collectifs", "Engorgements récurrents dans les grands ensembles", "Refoulements d'égouts en période de crue"], atout: "Proximité immédiate — nos artisans sont basés à 10 min d'Argenteuil" },
  { name: "Sarcelles", slug: "sarcelles", postalCode: "95200", description: "Grands ensembles avec réseaux collectifs des années 60, canalisations communes nécessitant des remplacements réguliers.", lat: 48.9953, lng: 2.3806, population: 58587, quartiers: ["Lochères", "Village", "Chardonnerettes", "Watteau"], problemesFrequents: ["Canalisations collectives en fonte usées", "Problèmes de pression dans les tours", "Racines dans les réseaux enterrés"], atout: "Équipe dédiée pour les réseaux collectifs de grande taille" },
  { name: "Cergy", slug: "cergy", postalCode: "95000", description: "Ville nouvelle avec infrastructures modernes, mais certains quartiers des années 70-80 présentent des canalisations à remplacer.", lat: 49.0363, lng: 2.0638, population: 66322, quartiers: ["Préfecture", "Grand Centre", "Axe Majeur", "Hauts-de-Cergy"], problemesFrequents: ["Vieillissement des réseaux des années 70-80", "Fuites sur canalisations PVC première génération", "Contre-pentes dans les lotissements"], atout: "Connaissance approfondie de l'agglomération de Cergy-Pontoise" },
  { name: "Pontoise", slug: "pontoise", postalCode: "95000", description: "Ville historique, réseaux anciens dans le centre médiéval, terrains instables près de l'Oise nécessitant une expertise spécifique.", lat: 49.0501, lng: 2.1007, population: 32092, quartiers: ["Centre historique", "Les Louvrais", "Marcouville", "Les Cordeliers"], problemesFrequents: ["Réseaux très anciens dans le centre médiéval", "Canalisations en grès fissurées", "Terrains instables en bord d'Oise"], atout: "Expérience des contraintes patrimoniales du centre historique" },
  { name: "Garges-lès-Gonesse", slug: "garges-les-gonesse", postalCode: "95140", description: "Quartiers résidentiels avec canalisations des années 60-70, interventions fréquentes sur les réseaux collectifs.", lat: 48.9731, lng: 2.4017, population: 43239, quartiers: ["Dame Blanche", "La Muette", "Les Doucettes", "Centre-ville"], problemesFrequents: ["Fonte corrodée dans les collectifs", "Bouchons calcaires récurrents", "Affaissements de canalisations sous voirie"], atout: "Interventions rapides grâce à notre proximité avec la Plaine de France" },
  { name: "Franconville", slug: "franconville", postalCode: "95130", description: "Zone pavillonnaire avec canalisations individuelles, terrain argileux nécessitant des techniques adaptées.", lat: 48.9886, lng: 2.2286, population: 36478, quartiers: ["Centre-ville", "Plessis-Bouchard", "Les Ébisoires", "La Gare"], problemesFrequents: ["Canalisations individuelles fissurées par le retrait-gonflement des argiles", "Racines de platanes dans les réseaux", "Joints défectueux sur PVC ancien"], atout: "Maîtrise des techniques adaptées aux sols argileux du Val d'Oise" },
  { name: "Goussainville", slug: "goussainville", postalCode: "95190", description: "Proximité de l'aéroport, réseaux mixtes entre ancien village et zones d'activités.", lat: 49.0333, lng: 2.4667, population: 31562, quartiers: ["Grandes Bornes", "Village", "Les Noues", "ZA Charles-de-Gaulle"], problemesFrequents: ["Réseaux vétustes dans le vieux village", "Canalisations industrielles sous-dimensionnées", "Vibrations aériennes fragilisant les joints"], atout: "Habilité à intervenir en zone aéroportuaire avec contraintes spécifiques" },
  { name: "Bezons", slug: "bezons", postalCode: "95870", description: "Bord de Seine, nappes phréatiques hautes compliquant les interventions sur canalisations enterrées.", lat: 48.9264, lng: 2.2122, population: 32234, quartiers: ["Centre-ville", "Colombes-Bezons", "Les Bords de Seine", "Champs-Lasniers"], problemesFrequents: ["Nappes phréatiques hautes rendant le terrassement complexe", "Canalisations en fonte corrodées par l'humidité", "Infiltrations en sous-sol fréquentes"], atout: "Équipement de pompage et blindage pour interventions en terrain inondable" },
  { name: "Ermont", slug: "ermont", postalCode: "95120", description: "Zone résidentielle dense, canalisations des années 50-70 nécessitant des remplacements progressifs.", lat: 48.9897, lng: 2.2583, population: 28815, quartiers: ["Centre-ville", "Les Chênes", "Cernay", "Gare d'Ermont-Eaubonne"], problemesFrequents: ["Fonte des années 50 en fin de vie", "Raccordements plomb à remplacer", "Engorgements dans les rues étroites du centre"], atout: "Techniques de chemisage sans tranchée idéales pour les rues étroites" },
  { name: "Eaubonne", slug: "eaubonne", postalCode: "95600", description: "Quartiers pavillonnaires de la vallée de Montmorency, canalisations individuelles sur terrain argileux.", lat: 48.9922, lng: 2.2828, population: 25637, quartiers: ["Centre-ville", "Les Gâtines", "La Chesnaie", "Les Noirs Bois"], problemesFrequents: ["Retrait-gonflement des argiles fissurant les canalisations", "PVC ancien cassant sous les allées", "Problèmes de pente sur terrains en coteau"], atout: "Diagnostic caméra systématique pour adapter la solution au terrain" },
  { name: "Saint-Gratien", slug: "saint-gratien", postalCode: "95210", description: "Proximité du lac d'Enghien, terrains humides et nappes hautes impactant les canalisations.", lat: 48.9694, lng: 2.2828, population: 21286, quartiers: ["Centre-ville", "Le Lac", "Les Raguenets", "Cygne d'Enghien"], problemesFrequents: ["Humidité permanente fragilisant les joints", "Canalisations en grès du centre ancien", "Remontées de nappes dans les sous-sols"], atout: "Solutions étanches renforcées pour zones à nappe haute" },
  { name: "Enghien-les-Bains", slug: "enghien-les-bains", postalCode: "95880", description: "Ville thermale, réseaux anciens du centre-ville, contraintes liées aux eaux souterraines et au lac.", lat: 48.9694, lng: 2.3089, population: 12029, quartiers: ["Centre thermal", "Bords du Lac", "Ormesson", "La Barre"], problemesFrequents: ["Réseaux centenaires dans le centre thermal", "Contraintes liées à la protection du lac", "Canalisations en plomb à remplacer d'urgence"], atout: "Intervention respectueuse des contraintes environnementales du lac" },
  { name: "Montmorency", slug: "montmorency", postalCode: "95160", description: "Coteau boisé, terrain en pente avec canalisations soumises aux mouvements de terrain argileux.", lat: 48.9897, lng: 2.3219, population: 21741, quartiers: ["Centre-ville", "Champeaux", "La Butte", "Les Champeaux"], problemesFrequents: ["Glissements de terrain endommageant les canalisations", "Racines de la forêt infiltrant les réseaux", "Forte pression gravitaire sur les descentes"], atout: "Expertise des terrains en pente et des techniques anti-racines" },
  { name: "Soisy-sous-Montmorency", slug: "soisy-sous-montmorency", postalCode: "95230", description: "Vallée de Montmorency, quartiers pavillonnaires avec canalisations des années 60-80.", lat: 48.9883, lng: 2.2994, population: 18152, quartiers: ["Centre-ville", "Les Économies", "Le Haut-Soisy", "La Gare"], problemesFrequents: ["PVC des années 60 devenu cassant", "Joints défaillants entre fonte et PVC", "Bouchons dans les regards de collecte"], atout: "Remplacement partiel ciblé pour limiter les coûts" },
  { name: "Taverny", slug: "taverny", postalCode: "95150", description: "Entre forêt et zone urbaine, réseaux mixtes avec problématiques de racines et terrain calcaire.", lat: 49.0025, lng: 2.2283, population: 27257, quartiers: ["Centre-ville", "Le Luat", "Vaucelles", "Les Écureuils"], problemesFrequents: ["Racines de la forêt de Montmorency dans les canalisations", "Dépôts calcaires obstruant les évacuations", "Contre-pentes dans les anciens lotissements"], atout: "Hydrocurage haute pression pour éliminer racines et calcaire" },
  { name: "Herblay-sur-Seine", slug: "herblay-sur-seine", postalCode: "95220", description: "Bord de Seine, terrains alluviaux et nappes phréatiques élevées, canalisations fragilisées par l'humidité.", lat: 48.9917, lng: 2.1686, population: 30590, quartiers: ["Centre-ville", "Les Bayonnes", "Le Haut-d'Herblay", "Les Cailloux Gris"], problemesFrequents: ["Terrain alluvial instable sous les canalisations", "Corrosion accélérée par l'humidité permanente", "Affaissements sur les berges de la Seine"], atout: "Matériaux PEHD résistants à l'humidité pour durabilité maximale" },
  { name: "Cormeilles-en-Parisis", slug: "cormeilles-en-parisis", postalCode: "95240", description: "Coteaux et carrières de gypse, terrain instable nécessitant des techniques de canalisation adaptées.", lat: 48.9714, lng: 2.2003, population: 25149, quartiers: ["Centre-ville", "Les Bois-Rochefort", "La Montagne", "Val-Fleuri"], problemesFrequents: ["Cavités de gypse provoquant des affaissements", "Terrain instable fissurant les canalisations", "Eaux de ruissellement surchargeant les réseaux"], atout: "Techniques de pose renforcée pour terrains à risque de dissolution" },
  { name: "Sannois", slug: "sannois", postalCode: "95110", description: "Butte témoin, terrain en pente avec canalisations sous pression gravitaire.", lat: 48.9711, lng: 2.2567, population: 27339, quartiers: ["Centre-ville", "Le Moulin", "Les Carreaux", "Le Frais-Village"], problemesFrequents: ["Forte pression gravitaire usant les canalisations en descente", "Érosion du terrain de la butte", "Bouchons fréquents dans les réseaux pentus"], atout: "Dimensionnement adapté aux fortes pentes pour éviter les surpressions" },
  { name: "Deuil-la-Barre", slug: "deuil-la-barre", postalCode: "95170", description: "Zone résidentielle de la vallée de Montmorency, canalisations pavillonnaires à entretenir.", lat: 48.9764, lng: 2.3264, population: 22506, quartiers: ["Centre-ville", "La Galathée", "Les Mortefontaines", "La Barre"], problemesFrequents: ["Canalisations pavillonnaires vieillissantes", "Raccordements non conformes aux normes actuelles", "Regards de visite bouchés par les feuilles"], atout: "Contrats d'entretien préventif pour prolonger la durée de vie des réseaux" },
  { name: "Villiers-le-Bel", slug: "villiers-le-bel", postalCode: "95400", description: "Mixte habitat collectif et pavillonnaire, réseaux des années 60-70 à remplacer.", lat: 49.0094, lng: 2.3933, population: 28491, quartiers: ["Village", "Les Carreaux", "Puits-la-Marlière", "Derrière-les-Murs"], problemesFrequents: ["Fonte des années 60 en fin de vie dans les collectifs", "Mélange de réseaux anciens et récents mal raccordés", "Affaissements sous les voiries communales"], atout: "Coordination avec les bailleurs sociaux pour interventions en collectif" },
  { name: "Arnouville", slug: "arnouville", postalCode: "95400", description: "Zone résidentielle de la Plaine de France, terrain plat argileux, canalisations sensibles aux mouvements de sol.", lat: 48.9878, lng: 2.4172, population: 14338, quartiers: ["Centre-ville", "Les Bouleaux", "La Lutèce", "Le Parc"], problemesFrequents: ["Retrait-gonflement des argiles fissurant les conduites", "Pente insuffisante causant des stagnations", "Canalisations en grès écrasées par le sol"], atout: "Pose sur lit de sable compacté pour stabiliser les canalisations en terrain argileux" },
  { name: "Gonesse", slug: "gonesse", postalCode: "95500", description: "Plaine de France, terrain argileux et réseaux anciens du bourg historique.", lat: 48.9872, lng: 2.4492, population: 27218, quartiers: ["Centre-ville", "La Fauconnière", "Les Marronniers", "ZAC Tulipes"], problemesFrequents: ["Réseaux du bourg historique en grès et fonte", "Terrain argileux provoquant des mouvements de sol", "Engorgements dans les lotissements des années 70"], atout: "Diagnostic complet avant intervention pour choisir la technique optimale" },
  { name: "Saint-Leu-la-Forêt", slug: "saint-leu-la-foret", postalCode: "95320", description: "Forêt de Montmorency, terrain boisé avec problématiques de racines infiltrant les canalisations.", lat: 49.0167, lng: 2.2458, population: 16069, quartiers: ["Centre-ville", "Le Bois-Clos", "La Plaine", "Les Sources"], problemesFrequents: ["Racines des arbres forestiers perforant les canalisations", "Terrain en pente aggravant l'érosion", "Humidité forestière accélérant la corrosion"], atout: "Barrières anti-racines et chemisage pour protéger durablement les canalisations" },
  { name: "Domont", slug: "domont", postalCode: "95330", description: "Lisière de la forêt de Montmorency, terrain mixte calcaire et argileux.", lat: 49.0289, lng: 2.3264, population: 15813, quartiers: ["Centre-ville", "Les Cités", "Les Petits-Prés", "La Sablière"], problemesFrequents: ["Calcaire obstruant les canalisations", "Sol mixte argile-calcaire instable", "Regards endommagés par le gel hivernal"], atout: "Traitement anti-calcaire et matériaux résistants au gel" },
  { name: "Montmagny", slug: "montmagny", postalCode: "95360", description: "Petite ville résidentielle, canalisations des quartiers pavillonnaires des années 50-70.", lat: 48.9736, lng: 2.3456, population: 14762, quartiers: ["Centre-ville", "Les Buttes", "Le Bois de la Chapelle", "La Mairie"], problemesFrequents: ["Canalisations en fonte des années 50 percées", "Raccordements plomb non conformes", "Infiltrations dans les caves des pavillons"], atout: "Remplacement rapide avec remise en état soignée des jardins" },
  { name: "Groslay", slug: "groslay", postalCode: "95410", description: "Village de la vallée de Montmorency, réseaux anciens du centre-bourg.", lat: 48.9867, lng: 2.3439, population: 8967, quartiers: ["Centre-bourg", "Les Prés", "La Fontaine", "Les Vignes"], problemesFrequents: ["Réseaux centenaires dans le vieux bourg", "Canalisations en grès fissurées par le temps", "Faible diamètre des conduites anciennes"], atout: "Chemisage sans tranchée pour préserver le charme du village" },
  { name: "Beauchamp", slug: "beauchamp", postalCode: "95250", description: "Zone pavillonnaire calme, canalisations individuelles nécessitant un entretien régulier.", lat: 49.0142, lng: 2.1928, population: 9227, quartiers: ["Centre-ville", "Les Chesneaux", "La Mare", "Les Pivoines"], problemesFrequents: ["Canalisations PVC des années 80 vieillissantes", "Bouchons liés à l'accumulation de graisses", "Regards de visite mal entretenus"], atout: "Forfaits entretien préventif pour canalisations pavillonnaires" },
  { name: "Pierrelaye", slug: "pierrelaye", postalCode: "95480", description: "Anciens champs d'épandage, terrain spécifique avec contraintes environnementales sur les canalisations.", lat: 49.0192, lng: 2.1594, population: 8750, quartiers: ["Centre-ville", "Les Champs d'Épandage", "La Vallée", "Le Village"], problemesFrequents: ["Sol pollué par les anciens épandages compliquant le terrassement", "Canalisations corrodées par les résidus chimiques", "Contraintes environnementales strictes sur les travaux"], atout: "Connaissance des contraintes réglementaires des anciens champs d'épandage" },
  { name: "Saint-Ouen-l'Aumône", slug: "saint-ouen-laumone", postalCode: "95310", description: "Bord de l'Oise, zone d'activités et résidentielle, réseaux mixtes industriels et domestiques.", lat: 49.0444, lng: 2.1119, population: 24752, quartiers: ["Centre-ville", "Liesse", "Épluches", "ZI des Béthunes"], problemesFrequents: ["Canalisations industrielles surdimensionnées mal raccordées au réseau domestique", "Terrain alluvial en bord d'Oise", "Rejets industriels corrodant les conduites"], atout: "Double compétence réseaux industriels et domestiques" },
  { name: "Osny", slug: "osny", postalCode: "95520", description: "Agglomération de Cergy-Pontoise, quartiers des années 70-80 avec canalisations à rénover.", lat: 49.0606, lng: 2.0631, population: 18085, quartiers: ["Centre-ville", "Immarmont", "Le Bois-Rochefort", "Les Grands Jardins"], problemesFrequents: ["PVC première génération devenu fragile", "Contre-pentes dans les lotissements en coteau", "Racines des espaces verts dans les canalisations"], atout: "Remplacement ciblé tronçon par tronçon pour maîtriser le budget" },
  { name: "Vauréal", slug: "vaureal", postalCode: "95490", description: "Ville nouvelle de Cergy-Pontoise, réseaux des années 70-80, terrain de coteau.", lat: 49.0381, lng: 2.0306, population: 17040, quartiers: ["Centre-ville", "Les Toupets", "Les Bussys", "L'Étoile"], problemesFrequents: ["Canalisations des années 70 en fin de vie", "Terrain en pente accentuant l'usure", "Infiltrations d'eaux pluviales dans les réseaux usés"], atout: "Intervention sur l'ensemble de l'agglomération de Cergy-Pontoise" },
  { name: "Jouy-le-Moutier", slug: "jouy-le-moutier", postalCode: "95280", description: "Cergy-Pontoise, quartiers résidentiels avec canalisations de 40-50 ans nécessitant des remplacements.", lat: 49.0119, lng: 2.0394, population: 17261, quartiers: ["Centre-ville", "Les Eguerets", "Vincourt", "Les Moissons"], problemesFrequents: ["Canalisations de 40-50 ans arrivant en fin de cycle", "Joints dégradés entre sections PVC", "Fuites souterraines non détectées depuis des années"], atout: "Détection de fuites par corrélation acoustique de dernière génération" },
  { name: "Éragny-sur-Oise", slug: "eragny-sur-oise", postalCode: "95610", description: "Bord de l'Oise, terrain alluvial, canalisations sensibles aux variations de nappe.", lat: 49.0175, lng: 2.1008, population: 17830, quartiers: ["Centre-ville", "Les Closeaux", "La Challe", "Le Village"], problemesFrequents: ["Nappe phréatique variable déstabilisant les canalisations", "Terrain alluvial meuble", "Refoulements en période de crue de l'Oise"], atout: "Pose de canalisations PEHD soudées pour étanchéité totale en zone inondable" },
  { name: "L'Isle-Adam", slug: "lisle-adam", postalCode: "95290", description: "Bord de l'Oise, ville pittoresque avec réseaux anciens et contraintes de zone inondable.", lat: 49.1128, lng: 2.2283, population: 12166, quartiers: ["Centre-ville", "Le Patis", "La Plage", "Nogent"], problemesFrequents: ["Zone inondable nécessitant des canalisations étanches", "Réseaux anciens dans le centre historique", "Érosion des berges fragilisant les conduites"], atout: "Expertise en zone inondable avec clapets anti-retour et joints renforcés" },
  { name: "Persan", slug: "persan", postalCode: "95340", description: "Nord du Val d'Oise, bord de l'Oise, réseaux mixtes anciens et récents.", lat: 49.1531, lng: 2.2728, population: 12245, quartiers: ["Centre-ville", "Les Deux Rivières", "La Gare", "Le Village"], problemesFrequents: ["Raccordements hétérogènes entre réseaux anciens et modernes", "Terrain en bord de rivière sujet aux crues", "Canalisations en fonte centenaires dans le centre"], atout: "Mise en conformité complète des raccordements anciens/modernes" },
  { name: "Beaumont-sur-Oise", slug: "beaumont-sur-oise", postalCode: "95260", description: "Bord de l'Oise, terrain alluvial, réseaux du centre historique nécessitant des interventions régulières.", lat: 49.1442, lng: 2.2867, population: 9985, quartiers: ["Centre-ville", "Les Coteaux", "Le Marais", "La Gare"], problemesFrequents: ["Réseaux du centre historique fragiles", "Terrain alluvial et nappes hautes", "Canalisations sous-dimensionnées pour les nouveaux quartiers"], atout: "Redimensionnement des canalisations pour adapter le réseau à la croissance urbaine" },
  { name: "Méry-sur-Oise", slug: "mery-sur-oise", postalCode: "95540", description: "Village en bord d'Oise, usine de traitement des eaux, réseaux bien entretenus mais anciens par endroits.", lat: 49.0681, lng: 2.1856, population: 9750, quartiers: ["Centre-village", "Les Coteaux", "Les Bords d'Oise", "Le Gibet"], problemesFrequents: ["Canalisations anciennes dans le vieux village", "Pression d'eau variable selon les quartiers", "Raccordements au réseau public non conformes"], atout: "Proximité de l'usine de traitement — coordination facilitée avec le service des eaux" },
  { name: "Auvers-sur-Oise", slug: "auvers-sur-oise", postalCode: "95430", description: "Village historique (Van Gogh), réseaux anciens du centre-bourg, contraintes patrimoniales.", lat: 49.0714, lng: 2.1700, population: 6893, quartiers: ["Centre-bourg", "Les Vallées", "Chaponval", "Le Valhermeil"], problemesFrequents: ["Contraintes architecturales dans le périmètre protégé", "Canalisations centenaires en grès et fonte", "Accès difficile dans les ruelles étroites du bourg"], atout: "Chemisage sans tranchée préservant l'intégrité du patrimoine historique" },
  { name: "La Roche-Guyon", slug: "la-roche-guyon", postalCode: "95780", description: "Vexin français, terrain calcaire et falaises, canalisations en zone rurale avec accès parfois complexe.", lat: 49.0808, lng: 1.6311, population: 477, quartiers: ["Le Village", "Les Falaises", "La Basse-Roche", "Haute-Isle"], problemesFrequents: ["Accès très difficile pour les engins de chantier", "Terrain rocheux calcaire compliquant le terrassement", "Canalisations rurales vétustes et sous-dimensionnées"], atout: "Mini-pelle et équipement compact pour accès en zone étroite et rurale" },
  { name: "Magny-en-Vexin", slug: "magny-en-vexin", postalCode: "95420", description: "Vexin français, bourg rural avec réseaux anciens, terrain calcaire du plateau.", lat: 49.1542, lng: 1.7881, population: 5879, quartiers: ["Centre-bourg", "La Croix-Blanche", "Les Hauteurs", "Route de Rouen"], problemesFrequents: ["Terrain calcaire dur rendant le terrassement coûteux", "Réseaux communaux anciens et mal cartographiés", "Faible débit d'évacuation dans les conduites anciennes"], atout: "Carottage et terrassement en terrain calcaire dur avec matériel adapté" },
];

export function getCityBySlug(slug: string): City | undefined {
  return cities.find((c) => c.slug === slug);
}

export function getAllCitySlugs(): string[] {
  return cities.map((c) => c.slug);
}

/** Haversine distance in km between two GPS points */
function haversineKm(lat1: number, lng1: number, lat2: number, lng2: number): number {
  const R = 6371;
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLng = ((lng2 - lng1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) * Math.cos((lat2 * Math.PI) / 180) * Math.sin(dLng / 2) * Math.sin(dLng / 2);
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

/** Returns the N geographically closest cities, excluding the given slug */
export function getNearbyCities(slug: string, count = 8): City[] {
  const city = getCityBySlug(slug);
  if (!city) return [];
  return cities
    .filter((c) => c.slug !== slug)
    .map((c) => ({ city: c, dist: haversineKm(city.lat, city.lng, c.lat, c.lng) }))
    .sort((a, b) => a.dist - b.dist)
    .slice(0, count)
    .map((item) => item.city);
}
